### ISSUE TITLE
Testing/Regression Tests

### ISSUE THREAD

**Issue by EGAlberts** [S2-group/UPISAS#2]
Right now adding functionality needs to verified ourselves afterwards. We should establish basic functionality with (unit) tests and run this after adding stuff.

**Comment by iliasger** [comment]
Started with this, implemented two unit tests here: #9

**Comment by iliasger** [comment]
Continuing unit tests in branch https://github.com/S2-group/UPISAS/tree/unit-testing, merging some progress back to main branch here #10

**Comment by iliasger** [comment]
First set of unit tests (16 in total, testing both the exemplar and the strategy) are now merged via #11

**Comment by iliasger** [comment]
Unit tests done, will open new issue if needed for other (regression?) tests.
